export const ROLE_ADMIN = 1
export const ROLE_TEACHER = 2
export const ROLE_MANAGER = 4
export const ROLE_SALER = 5
export const ROLE_ACCOUNTANT = 6
export const ROLE_ACADEMIC = 7
export const ROLE_PARENT = 8
export const ROLE_STUDENT = 3

export const MANAGEMENT_ROLES = [ROLE_ADMIN, ROLE_TEACHER, ROLE_MANAGER, ROLE_SALER, ROLE_ACCOUNTANT, ROLE_ACADEMIC]
export const NORMAL_ROLES = [ROLE_PARENT, ROLE_STUDENT]
